#! /usr/bin/env node
const challenges = require('./sets');
const program = require('commander');
const colors = require('colors');

function runOne(n) {
  if (!challenges[n]) {
    throw new Error(`Failed to run ${n}. Missing sets/*/${n}.js.`);
  }

  console.log(colors.bold(`*** Challenge ${n} ***`));
  if (challenges[n].describe) console.log(challenges[n].describe);

  const retVal = challenges[n].run();
  if (typeof retVal !== 'undefined') {
    console.log(colors.green('Return Value:'), retVal);
  }
}

function runAll() {
  Object.keys(challenges).forEach(challenge => {
    if (challenge === '19') {
      console.log('Skipping 19 because it is interactive.');
      return;
    }
    runOne(challenge);
  });
}

program
  .version('0.0.1')
  .option('-s --single [n]', 'The individual challenge to run.', parseInt)
  .parse(process.argv);

const challengeNumber = program.single;
try {
  if (!challengeNumber) runAll();
  else runOne(challengeNumber);
} catch (e) {
  if (e.message) {
    console.log(colors.bgRed('Failure:'), e.stack);
  } else {
    console.log(colors.bgRed('Error: Exception with no `.message`. Please throw Error objects.'));
    console.log(e);
  }
}
